stages:
  - test

# Test job for the 'test' stage
test:
  image: rocker/r-ver:4.1.0    
  stage: test
  script:
    - apt-get update -qq && apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
    - Rscript -e "install.packages('devtools')"  # Install devtools for checking
    - Rscript -e "devtools::check()"             # Run the R CMD check for your package
  only:
    - main        

