image: rocker/r-ver:4.3.1

stages:
  - check

R-CMD-check:
  stage: check
  script:
    - apt-get update -o Acquire::Retries=3
    - apt-get install -y --no-install-recommends \
        libcurl4-openssl-dev \
        libssl-dev \
        libxml2-dev \
        zlib1g-dev \
        libgit2-dev \
        pandoc
    - Rscript -e 'install.packages("devtools", repos = "https://cloud.r-project.org")'
    - Rscript -e 'devtools::check()'
